#!/bin/bash
cd /home/megamek/megamek
#/usr/bin/java -Xmx1024m -jar MegaMek.jar -dedicated -port 2346 -password qwweassdzxxc
/usr/bin/java -jar MegaMek.jar -dedicated -port 2346 -password qwweassdzxxc
exit 0
