#!/usr/bin/perl

my $MEGAMEKDIR = "/home/mekuser/mekhq";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep MegaMek.jar|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Megamek...\n";
		if (-f "$MEGAMEKDIR/nostart")
		{
			print "Removing $MEGAMEKDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$MEGAMEKDIR/nostart");
		}
		# Start the screen process
		system("nohup $MEGAMEKDIR/startmegamek > /tmp/MegamekStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Megamek process...\n";
	system("touch '$MEGAMEKDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall MegaMek");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$MEGAMEKDIR/nostart")
	{
		print("Removing $MEGAMEKDIR/nostart\n");
		unlink("$MEGAMEKDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall MegaMek");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Megamek Server Running\n");
	}
	else
	{
		print("Megamek Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
